@baseUrl = http://localhost:3000/api
@adminToken = {{admin_login.response.body.data.accessToken}}

### Admin Login
# @name admin_login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@minispod.com",
  "password": "password123"
}



### Get all services
GET {{baseUrl}}/admin/k8s/services
Authorization: Bearer {{adminToken}}